CREATE DATABASE FARMACIA_EL_CARMEN
GO
USE FARMACIA_EL_CARMEN
GO

CREATE TABLE CLIENTE(
	ID_CLIENTE INT IDENTITY PRIMARY KEY,
	NOMBRE VARCHAR(20) NOT NULL,
	APELLIDO VARCHAR(20) NOT NULL,
	DIRECCION VARCHAR(100) NOT NULL,
	TELFIJO VARCHAR(8) NOT NULL,
	CELULAR VARCHAR(8) NOT NULL,
	CORREO VARCHAR(45) NOT NULL,
	USUARIO VARCHAR(20) UNIQUE NOT NULL,
	CONTRASENIA VARCHAR(15) NOT NULL,
	TIPOCLIENTE VARCHAR(15) NOT NULL
	CHECK (TIPOCLIENTE IN ('COMUN', 'MAYOREO'))
);

CREATE TABLE ENCARGADO(
	ID_ENCARGADO INT IDENTITY PRIMARY KEY,
	NOMBRE VARCHAR(20) NOT NULL,
	APELLIDO VARCHAR(20) NOT NULL,
	EDAD INT NOT NULL,
	FACHA_NACIMIENTO DATE NOT NULL,
	DIRECCION VARCHAR(100) NOT NULL,
	CORREO VARCHAR(45) NOT NULL,
	USUARIO VARCHAR(20) UNIQUE NOT NULL,
	CONTRASENIA VARCHAR(15) NOT NULL
);

CREATE TABLE ADMINISTRADOR(
	ID_ADMIN INT IDENTITY PRIMARY KEY,
	NOMBRE VARCHAR(20) NOT NULL,
	APELLIDO VARCHAR(20) NOT NULL,
	EDAD INT NOT NULL,
	FACHA_NACIMIENTO DATE NOT NULL,
	DIRECCION VARCHAR(100) NOT NULL,
	CORREO VARCHAR(45) NOT NULL,
	USUARIO VARCHAR(20) UNIQUE NOT NULL,
	CONTRASENIA VARCHAR(15) NOT NULL
);

CREATE TABLE MERCADERIA(
	ID_MERC INT IDENTITY PRIMARY KEY,
	NOMBRE VARCHAR(35) NOT NULL,
	FECHA_VEN DATE NOT NULL,
	CANTIDAD INT NOT NULL,
	PRECIO DECIMAL(5,2) NOT NULL,
	IMAGEN IMAGE,
	TIPO VARCHAR(30) NOT NULL
);
GO

CREATE TABLE COMPRA(
	ID_COMPRA INT IDENTITY PRIMARY KEY NOT NULL,
	FECHA_COMPRA DATE NOT NULL,
	CANTIDAD INT NOT NULL,
	ID_MERC INT,
	ID_CLIENTE INT
	CONSTRAINT FK_MERCADERIA FOREIGN KEY(ID_MERC) REFERENCES MERCADERIA(ID_MERC),
	CONSTRAINT FK_CLIENTE FOREIGN KEY(ID_CLIENTE) REFERENCES CLIENTE(ID_CLIENTE)
);

CREATE TABLE SOLICITUD(
	ID_SOLICITUD INT IDENTITY PRIMARY KEY,
	NOMBRE_MEDICAMENTO VARCHAR(35) NOT NULL,
	CANTIDAD INT NOT NULL,
	FECHA DATE NOT NULL,
	ID_ENCARGADO INT,
	CONSTRAINT FK_ID_ENCARGADO FOREIGN KEY(ID_ENCARGADO) REFERENCES ENCARGADO(ID_ENCARGADO)
);

CREATE TABLE BODEGA(
	ID_BODEGA VARCHAR(10) PRIMARY KEY,
	USUARIO VARCHAR(25),
	CONTRASEÑA VARCHAR(25),
	ID_MERC INT,
	NOMBRE_PRODUCTO VARCHAR(35) NOT NULL,
	FECHA_DE_VENCIMIENTO DATE NOT NULL,
	EXISTENCIAS INT NOT NULL
);

CREATE TABLE INVENTARIO(
	ID_INVENTARIO INT IDENTITY PRIMARY KEY,
	RESPALDO_FACTURA VARCHAR(100) NOT NULL,
	ID_BODEGA VARCHAR(10)
	CONSTRAINT FK_ID_BODEGA FOREIGN KEY(ID_BODEGA) REFERENCES BODEGA(ID_BODEGA)
);
GO

--procedimiento almacenado para el logueo de usuarios

CREATE PROC LOGEO_ENCARGADO
	@USUARIO VARCHAR(25),
	@CONTRASEÑA VARCHAR(25)
AS
BEGIN
	SELECT COUNT(USUARIO) FROM ENCARGADO WHERE USUARIO = @USUARIO
	AND CONTRASENIA = @CONTRASEÑA
END
GO

CREATE PROC LOGEO_CLIENTE
	@USUARIO VARCHAR(25),
	@CONTRASEÑA VARCHAR(25)
AS
BEGIN
	SELECT COUNT(USUARIO) FROM CLIENTE WHERE USUARIO = @USUARIO
	AND CONTRASENIA = @CONTRASEÑA
END
GO

CREATE PROC LOGEO_ADMIN
	@USUARIO VARCHAR(25),
	@CONTRASEÑA VARCHAR(25)
AS
BEGIN
	SELECT COUNT(USUARIO) FROM ADMINISTRADOR WHERE USUARIO = @USUARIO
	AND CONTRASENIA = @CONTRASEÑA
END
GO

CREATE PROC LOGEO_BODEGA
	@USUARIOB VARCHAR(25),
	@CONTRASEÑA VARCHAR(25)
AS
BEGIN
	SELECT COUNT(@USUARIOB) FROM BODEGA WHERE USUARIO = @USUARIOB
	AND CONTRASEÑA = @CONTRASEÑA
END
GO

--Insercion de datos

	SELECT * FROM CLIENTE
INSERT INTO CLIENTE VALUES ('Efenver','Campos','Soyacity', '7644-3944', 
'efenver.zarceno','efenver','12345','mayoreo')
SELECT * FROM CLIENTE WHERE TIPOCLIENTE = 'COMUN'

UPDATE CLIENTE SET CORREO = 'eliza110915', CONTRASENIA = '200' WHERE USUARIO = 'Raquel_Hernandez'


INSERT INTO MERCADERIA VALUES ('Panadol Azul', '13/08/2022', 100, 7, 'Analgesico')
INSERT INTO MERCADERIA VALUES('Panadol Ultrafuerte', '15/10/2020', 300, 8, 'Analgesico')
INSERT INTO MERCADERIA VALUES('Clorferinamina', '15/10/2020', 160, 10, 'Histaminico')
INSERT INTO MERCADERIA VALUES('Anaflat', '30/06/2020', 100, 6, 'Simeticona')
INSERT INTO MERCADERIA VALUES('Ranitidina', '15/10/2020', 200, 8, 'Analgesico')

UPDATE CLIENTE SET NOMBRE = 'pechuga', APELLIDO = 'navarro',
                DIRECCION = 'Soyacity', TELFIJO = '1233456', CELULAR = '4455555',
                CORREO = 'pechugin', CONTRASENIA = '30'
                WHERE (USUARIO = 'pechuga')

SELECT * FROM ENCARGADO
SELECT * FROM CLIENTE